# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kisi',
            fields=[
                ('KisiID', models.IntegerField(primary_key=True, serialize=False)),
                ('Adi', models.CharField(max_length=120, verbose_name='Adı')),
                ('Soyadi', models.CharField(max_length=120, verbose_name='Soyadı')),
                ('Resim', models.ImageField(blank=True, null=True, upload_to='')),
                ('KullaniciID', models.IntegerField(verbose_name='Kullanıcı ID')),
            ],
        ),
        migrations.CreateModel(
            name='KisiEposta',
            fields=[
                ('KisiEpostaID', models.IntegerField(primary_key=True, serialize=False)),
                ('Eposta', models.CharField(max_length=150, verbose_name='Eposta')),
                ('Tur', models.SmallIntegerField(verbose_name='Tür')),
                ('Kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Epostas', to='rehber.Kisi', verbose_name='Kisi')),
            ],
        ),
        migrations.CreateModel(
            name='KisiTelefon',
            fields=[
                ('KisiTelefonID', models.IntegerField(primary_key=True, serialize=False)),
                ('Telefon', models.CharField(max_length=12, verbose_name='Telefon')),
                ('Tur', models.SmallIntegerField(verbose_name='Tür')),
                ('Kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Telefons', to='rehber.Kisi', verbose_name='Kişi')),
            ],
        ),
    ]
