# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0002_auto_20170506_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='KisiID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kisieposta',
            name='KisiEpostaID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kisitelefon',
            name='KisiTelefonID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
